In [2]:
import torch

In [3]:
print(torch.__version__)

1.10.0


In [4]:
import numpy as np

In [5]:
lst = [3,4,5,6]
arr = np.array(lst)

In [7]:
arr

array([3, 4, 5, 6])

In [6]:
arr.dtype

dtype('int32')

In [9]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [10]:
#indexing familiar to numpy
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [11]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [12]:
tensors[2]

tensor(5, dtype=torch.int32)

In [13]:
tensors[3] = 100

In [14]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [19]:
arr

array([  3,   4,   5, 100])

In [16]:
#prevent this by using torch.Tensor
tensor_arr = torch.tensor(arr)
tensor_arr 

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [18]:
tensor_arr[3] = 120 
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


In [20]:
torch.zeros(2,3,dtype = torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.ones(2,3,dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [25]:
np.arange(0,15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
at = torch.tensor(np.arange(0,15).reshape(5,3))
at

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [38]:
at[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

In [22]:
a = torch.tensor([3,4,5],dtype = torch.float)
b = torch.tensor([4,5,6],dtype = torch.float)

In [23]:
print(a+b)

tensor([ 7.,  9., 11.])


In [24]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [39]:
c = torch.zeros(3)

In [40]:
torch.add(a,b,out = c)

tensor([ 7.,  9., 11.])

In [41]:
c

tensor([ 7.,  9., 11.])

In [42]:
torch.add(a,b).sum() #[7,9,11]

tensor(27.)

In [46]:
x = torch.tensor([3,4,5],dtype = torch.float)
y = torch.tensor([4,5,6],dtype = torch.float)


In [47]:
x.mul(y)

tensor([12., 20., 30.])

In [48]:
# 3*4 + 5*4 + 6*5

In [49]:
x.dot(y)

tensor(62.)